### ISSUE TITLE
now it's not work

### ISSUE THREAD

**Issue by smartzer** [zgs225/alfred-youdao#15]
when i use "yd XXX" , the alfred will search for the translate result,but it will jump to the web search for "XXX",it seems not work？

<img width="577" alt="1" src="https://user-images.githubusercontent.com/29965801/42794612-4ac86b9c-89b2-11e8-946e-e29199a73813.png">

<img width="573" alt="2" src="https://user-images.githubusercontent.com/29965801/42794622-568a685e-89b2-11e8-89ac-d6f22121c001.png">

sincerely yours.

**Comment by zgs225** [comment]
有道的账户欠费了…… 我已经充值了。应该很快就能使用了。
