### ISSUE TITLE
您好，屏幕取词怎么设置

### ISSUE THREAD

**Issue by supergaga** [zgs225/alfred-youdao#21]
屏幕取词功能怎么用呢

**Comment by zgs225** [comment]
到 Alfred 的设置里面，找到这个扩展，然后设置屏幕取词的快捷键。

**Comment by supergaga** [comment]
![image](https://user-images.githubusercontent.com/13994894/55372458-67d23300-5534-11e9-8967-1fc397b1c7a1.png)

但是这个框里面我不能设置按键

**Comment by zgs225** [comment]
<img width="1106" alt="屏幕快照 2019-04-02 12 26 23" src="https://user-images.githubusercontent.com/3501131/55376512-47f63b80-5543-11e9-8a45-724f71086946.png">

**Comment by supergaga** [comment]
好的  谢谢  解决了
