### ISSUE TITLE
有道账户欠费停

### ISSUE THREAD

**Issue by chenhy97** [zgs225/alfred-youdao#22]
好像今天用不了了，看了一下alfred的debug模式，提示下面的错误。
![1](https://user-images.githubusercontent.com/33004472/56941552-c0065000-6b47-11e9-8390-388f8bc26e34.png)

**Comment by zhisheng17** [comment]
同不能用啦

**Comment by zgs225** [comment]
已经续费了。都是我自己充值的，难受啊。现在费用一天能有 10 块钱了。

**Comment by zhisheng17** [comment]
大佬留个微信或者支付宝二维码 @zgs225

**Comment by zgs225** [comment]
@zhisheng17 感谢你的慷慨。

![A5](https://user-images.githubusercontent.com/3501131/56950069-28185e80-6b67-11e9-8937-ea3518b98e52.png)

**Comment by lylehust** [comment]
能否提供paypal或buy me a coffee链接。我没有支付宝，不能支付。谢谢！
