### ISSUE TITLE
errcode 401 是什么原因?

### ISSUE THREAD

**Issue by devbitroom** [zgs225/alfred-youdao#23]
![image](https://user-images.githubusercontent.com/49862284/59751703-9948d800-92b3-11e9-8f20-53267c494dd6.png)

**Comment by zgs225** [comment]
有其他的 workflow 也是用 yd 吧，这个不是这个项目的 workflow

**Comment by zgs225** [comment]
<img width="557" alt="屏幕快照 2019-06-19 17 18 02" src="https://user-images.githubusercontent.com/3501131/59753214-399ffc00-92b6-11e9-9813-37c49ca1efa8.png">
