### ISSUE TITLE
release怎么进？

### ISSUE THREAD

**Issue by jiec-msft** [zgs225/alfred-youdao#24]
弱弱地问一句，release在哪里？

**Comment by reiy-leo** [comment]
弱弱的提示一下，

<img width="771" alt="image" src="https://user-images.githubusercontent.com/2398514/61439111-7f161e80-a973-11e9-8c14-d233e255f500.png">
 
切换到Code, 

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/2398514/61439170-935a1b80-a973-11e9-9e4d-6c48d95a9e4e.png">

在commits, branches后面。
