### ISSUE TITLE
这个原先都是你付费的吗?

### ISSUE THREAD

**Issue by qbmiller** [zgs225/alfred-youdao#28]
我建了个有道翻译实例, 204元 500w字符, 有效期90天....

**Comment by qbmiller** [comment]
> 我才发现，前几天yd用不了了，今天就尝试着命令行下运行：
> 
> ```shell
> [i] 2020/04/17 13:26:44 agent.go:48: Cache count: 336
> [i] 2020/04/17 13:26:44 agent.go:31: Cache miss
> panic: [401] 账户已经欠费停
> 
> goroutine 1 [running]:
> ```
> 
> 所以之前一直是作者付费承担的吗 QAQ

我自建那个可以用; 还有个 google 翻译的. 但只能输入中文..
![image](https://user-images.githubusercontent.com/7335567/79536429-a2acf780-80b2-11ea-94c7-09e3cb046be7.png)

**Comment by tete1030** [comment]
#22 的确是作者自付的，感激。如果可以发起个小规模众筹，每年一起筹集这笔费用，还是很愿意支持的

**Comment by zgs225** [comment]
是的哦。很感谢你使用。刚刚续费了。

**Comment by tete1030** [comment]
真的很感谢您的无私分享！我也默默用了几年，一直感觉非常方便好用，得知您一直默默付费维护时我还是蛮惊讶的。请问#22 中的二维码还是有效的吗？还未工作能给的不多，想尽点绵薄之力
