### ISSUE TITLE
我注册了有道智云有50元体验可用一个月

### ISSUE THREAD

**Issue by woolson** [zgs225/alfred-youdao#29]
### 账号信息

> 有效期：2020-04-22 ~ 2020-05-22

```
zhiyun_id: 1d27f7a9a0d84c27
zhiyun_key: yUZ4VRNxOtxMsLs1DsQOSXzhQWg8LYva
```

⚡️ 如果有人没注册的，可以等这个号到期后进行注册**共享**，大家一起白嫖。

**Comment by woolson** [comment]
![image](https://user-images.githubusercontent.com/27878293/79965850-21dd6980-84bf-11ea-953d-fa7dd39e7937.png)

**Comment by woolson** [comment]
需要使用的朋友，需提供IP设置IP白名单（防止滥用）

**Comment by climbingDog** [comment]
也可以自己注册的吧，貌似免费id有调用次数限制？

**Comment by zgs225** [comment]
这段时间忘记充值了。我回头补上。

**Comment by zgs225** [comment]
已经续费了。
