### ISSUE TITLE
请问怎么安装？

### ISSUE THREAD

**Issue by lorenzt** [zgs225/alfred-youdao#6]
下载之后怎么安装？

**Comment by zgs225** [comment]
Releases里面下载后打开就行了。

**Comment by lyfoppa** [comment]
还是不会安装，是把这个包放在哪个文件夹里吗？

**Comment by zgs225** [comment]
首先你需要有 Alfred 这个软件，然后你下载 https://github.com/zgs225/alfred-youdao/releases 里面的最新版本，直接打开就可以安装了。
