### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by psychopasss** [zgs225/alfred-youdao#7]
你好，开发者，最近在用这个，不过与之前的我用的一个 workfolw 对比，个人感觉显示结果可以优化一下。请看下图，如果有需要，可以提供一下，另一个包的源码。谢谢
![](https://i.loli.net/2018/01/19/5a6150699d82c.png)

**Comment by zgs225** [comment]
翻译结果分成单词解释、翻译和网络例句三个部分。你是指它的哪一个显示比我的好？

单词解释的地方，我看它把几条解释合成了一条。这样长的语句显示不全，只能通过 ... 去省略了。不觉得好。

翻译的显示你给的这张图上没有看到它的示例。

网络例句部分它的英文和中文的显示次序和我的相反。你是指这一部分它的更好吗？

**Comment by yanzhenyu** [comment]
谢谢回复，是这样的，我希望：
我输入的是中文，结果中，英文显示为主标题，中文为副标题；输入的是英文，结果中，中文显示为主标题，英文为副标题。这里友好一点，因为大部分情况下，我想要的结果，会以主标题显示

**Comment by zgs225** [comment]
在我的结果中，你的需求应该是在网络释义那一个部分吧。如图：

<img width="566" alt="2018-01-22 10 36 40" src="https://user-images.githubusercontent.com/3501131/35202894-4769b23a-ff60-11e7-91fd-09a27c84cb8b.png">

对于网络释义的部分，我之前的理解是，这部分的结果大部分都是例句和例句的翻译，所以应该是例句更应该首先被显示出来。

不过，现在你提出了别的看法，我会再想想这块的显示。最好还能有一些其他的人的意见，看看他们是觉得哪种更好。

**Comment by yanzhenyu** [comment]
纯属个人意见。🤝

**Comment by zgs225** [comment]
十分感谢你提意见。很多时间你们提的意见是我更新代码的动力。

**Comment by Chris-Bai** [comment]
你好，我也有这样的困惑。对于英文来说，网络释义弹出来的例句可以给我们一些很棒的英文用法。但对于中文来说，就不需要这些，后面突出显示的则是中文例句，可能我们更需要的是中文例句对应的英文翻译。。

**Comment by zgs225** [comment]
@Chris-Bai 我刚才对比了一下中文和英文查询结果，我明白你的意思了。在中文情况下，应该是显示英文例句为主。我会对中文查询结果做一下改进。
